@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
top to bottom direction

Container(DeviceService, "Device Service", "Go") {
  Component(DeviceAPI, "Device API", "Обработка запросов регистрации, удаления и получения информации об устройствах")
  Component(DeviceHandler, "Device Handler", "Валидация данных и реализация логики подключения новых устройств")
  Component(DeviceRepository, "Device Repository", "Хранение метаданных и учётных данных устройств")
  Component(EventPublisher, "Event Publisher", "Отправка событий жизненного цикла устройств во внешние системы")
}

Rel(DeviceAPI, DeviceHandler, "Передаёт запросы на обработку")
Rel(DeviceHandler, DeviceRepository, "Чтение и запись данных об устройствах")
Rel(DeviceHandler, EventPublisher, "Публикует события регистрации устройств")
@enduml